description = "RabbitMQ integration"

dependencies {
    implementation project(":common-utils:config")
    implementation project(":common-utils:core")
    implementation project(":common-utils:awaitility")
    implementation project(":testng-extensions")

    implementation libs.rabbitmq
    api "org.apache.commons:commons-lang3"
}
