description = "ReportPortal TestNG integration"

dependencies {
    implementation project(":integrations:reportportal:reportportal-core")
    implementation project(":common-utils:core")
    implementation project(":common-utils:config")
    implementation project(":testng-extensions")

    implementation libs.reportportal
    implementation libs.allure.testng
    api "org.apache.commons:commons-lang3"

    testImplementation project(":integrations:rest-assured")
    testImplementation libs.mockito.core
}
