services:
  dind:
    image: docker:29.8-dind@sha256:5efed980cba3fc126cf54e21a5a6ff8849d05b6e0623d6e7612f48e9cd6cd17e
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
    volumes:
      - dind-data:/var/lib/docker

  runner:
    image: myoung34/github-runner:2.337.0@sha256:03daab12e729883bdb1f58c2b6962a4f394c6b43d3d6bffd272aeae335f26a32
    depends_on:
      - dind
    environment:
      REPO_URL: ${REPO_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      LABELS: ${RUNNER_LABELS}
      RUNNER_EPHEMERAL: "true"
      DISABLE_AUTO_UPDATE: "true"
      DOCKER_HOST: tcp://dind:2375
      DOCKER_TLS_CERTDIR: ""
      RUNNER_TOOL_CACHE: /opt/hostedtoolcache
    volumes:
      - runner-toolcache:/opt/hostedtoolcache
      - runner-gradle-cache:/home/runner/.gradle

volumes:
  dind-data:
  runner-toolcache:
  runner-gradle-cache:
