_commit: v2.12.3-2-g48c1b15
_src_path: https://github.com/quokkify/project-toolkit.git
allure_categories_file: tools/allure/categories.json
allure_external_artifact_max_count: 50
allure_external_artifact_min_count: 24
allure_external_artifact_prefix: allure-results-
allure_external_workflow_name: Run tests
allure_external_workflow_path: .github/workflows/test.yml
allure_pages_url: https://quokkify.github.io/q4j
allure_publish_pages: true
allure_report: true
components: []
docker: false
project_name: Q4J
release_please: false
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
- default
- github-actions
- java
toolkit_version: v2.12.3
