dependencies {
    implementation project(":common-utils:core")
    implementation project(":common-utils:awaitility")
    implementation project(":common-utils:config")
    api project(":common-utils:jackson:json")
    implementation project(":testng-extensions")
    implementation libs.jjschema

    implementation libs.owner
    api libs.rest.assured
    api libs.json.schema.validator
    api libs.allure.rest.assured

    testImplementation libs.allure.testng
    testImplementation libs.mockito.core

    implementation platform(libs.jackson.bom)
    api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    api "org.assertj:assertj-core"
}
