description = "TestRail core integration"

dependencies {
    implementation project(":common-utils:config")
    implementation project(":common-utils:core")
    implementation project(":common-utils:jackson:json")
    implementation libs.feign.core
    implementation libs.feign.jackson
    implementation libs.feign.okhttp
    api "org.apache.commons:commons-lang3"
}
