description = "TestRail core integration"

dependencies {
    implementation project(":common-utils:config")
    implementation project(":common-utils:core")
    implementation project(":common-utils:jackson:json")
    implementation "io.github.openfeign:feign-core:${feign}"
    implementation "io.github.openfeign:feign-jackson:${feign}"
    implementation "io.github.openfeign:feign-okhttp:${feign}"
    api "org.apache.commons:commons-lang3"
}
