subprojects {
    repositories {
        mavenCentral()
        maven {
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
            mavenContent {
                snapshotsOnly()
            }
        }
        maven {
            url = "https://packages.atlassian.com/maven/repository/public"
            name = "atlassian-public"
        }
    }

    dependencies {
        constraints {
            api rootProject.libs.jackson.bom
            api rootProject.libs.owner
            api rootProject.libs.slf4j.api
            api rootProject.libs.slf4j.jcl
            api rootProject.libs.log4j.api
            api rootProject.libs.log4j.core
            api rootProject.libs.log4j.slf4j2.impl
            api rootProject.libs.assertj.core
            api rootProject.libs.hamcrest
            api rootProject.libs.awaitility
            api rootProject.libs.testng
            api rootProject.libs.allure.testng
            api rootProject.libs.commons.io
            api rootProject.libs.commons.lang3
            api rootProject.libs.commons.text
            api rootProject.libs.mockito.core
        }

        compileOnly rootProject.libs.jetbrains.annotations
        annotationProcessor rootProject.libs.jetbrains.annotations
        testCompileOnly rootProject.libs.jetbrains.annotations
        testAnnotationProcessor rootProject.libs.jetbrains.annotations

        if (project.path != ":testng-extensions") {
            testImplementation project(":testng-extensions")
        }
        testImplementation "org.assertj:assertj-core"
        testImplementation "org.apache.logging.log4j:log4j-core"
        testImplementation "org.apache.logging.log4j:log4j-slf4j2-impl"

        compileOnly rootProject.libs.spotbugs.annotations
        testCompileOnly rootProject.libs.spotbugs.annotations
    }
}