description = "Selenide BrowserUpProxy integration for HAR recording and request interception"

dependencies {
    implementation project(":integrations:selenide")
    implementation project(":common-utils:config")
    compileOnly project(":testng-extensions")

    implementation "com.codeborne:selenide-proxy:${selenide}"
    api "de.sstoehr:har-reader:${harReader}"
    testImplementation project(":testng-extensions")
    testImplementation "io.qameta.allure:allure-testng:${allure}"

    api "org.assertj:assertj-core"
}
