description = "TestRail description provider for ReportPortal"

dependencies {
    implementation project(":integrations:reportportal:testng")
    implementation project(":integrations:testrail:testrail-core")
    implementation project(":common-utils:config")

    api "org.apache.commons:commons-lang3"
}
