description = "Tyrus WebSocket client wrapper for test automation"

dependencies {
    implementation project(":common-utils:config")
    implementation project(":common-utils:core")
    implementation project(":common-utils:awaitility")
    implementation project(":common-utils:jackson:json")
    implementation project(":testng-extensions")

    implementation libs.tyrus.standalone.client

    testImplementation libs.tyrus.container.grizzly.server
}
