dependencies {
    implementation project(":common-utils:core")
    implementation project(":common-utils:config")
    implementation project(":testng-extensions")
    implementation libs.bouncy.castle
    api "org.assertj:assertj-core"
    api "org.apache.logging.log4j:log4j-slf4j2-impl"
    api "org.slf4j:jcl-over-slf4j"
    api "org.slf4j:slf4j-api"
}
