dependencies {
    api platform(libs.jackson.bom)

    api "com.fasterxml.jackson.core:jackson-databind"
    api "com.fasterxml.jackson.core:jackson-annotations"
    api "com.fasterxml.jackson.core:jackson-core"
    api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    api "com.fasterxml.jackson.datatype:jackson-datatype-jdk8"
}
