FROM nginx:1.31.6@sha256:60f0d4e986561e08804f75c211dcaf7fc5455699eada29f42cbe8a0a7253dd86

COPY conf.d/ /etc/nginx/conf.d/
COPY html/ /usr/share/nginx/html/

RUN test -f /etc/nginx/conf.d/10_site.conf
