FROM nginx:1.31.4@sha256:b34848eff6db786b6b1282d3a9c3fd0b5563dfb6d261df4923378b419e0d24f0

COPY conf.d/ /etc/nginx/conf.d/
COPY html/ /usr/share/nginx/html/

RUN test -f /etc/nginx/conf.d/10_site.conf
