server {
    listen 80 default_server;
    listen [::]:80;
    server_name localhost;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /table {
        return 301 /table/;
    }
    location = /google {
        return 301 /google/;
    }
    location = /uploads {
        return 301 /uploads/;
    }
    location = /horizontal_table {
        return 301 /horizontal_table/;
    }

    location /external/speedtest/ {
        alias /usr/share/nginx/html/speedtest/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location ^~ /uploads/files/ {
        types { text/plain txt; }
        default_type text/plain;

        add_header Content-Disposition "attachment; filename=\"$download_name\"" always;
        add_header X-Content-Type-Options "nosniff" always;

        try_files $uri =404;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        try_files $uri =404;
    }
}
