dependencies {
    implementation project(":common-utils:core")
    implementation project(":common-utils:file")
    implementation project(":common-utils:awaitility")
    implementation project(":common-utils:config")
    implementation project(":testng-extensions")

    implementation libs.classgraph
    implementation libs.hibernate.core
    implementation libs.hibernate.c3p0
    implementation libs.jakarta.persistence.api
    implementation libs.hibernate.type
    implementation "com.querydsl:querydsl-jpa:${libs.versions.querydsl.get()}:jakarta"
    implementation "jakarta.annotation:jakarta.annotation-api:3.0.0"
    annotationProcessor "com.querydsl:querydsl-apt:${libs.versions.querydsl.get()}:jakarta"
    annotationProcessor libs.jakarta.persistence.api
    annotationProcessor "jakarta.annotation:jakarta.annotation-api:3.0.0"
    testAnnotationProcessor "com.querydsl:querydsl-apt:${libs.versions.querydsl.get()}:jakarta"
    testAnnotationProcessor libs.jakarta.persistence.api
    testAnnotationProcessor "jakarta.annotation:jakarta.annotation-api:3.0.0"
    api libs.assertj.core
    testRuntimeOnly libs.h2
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += [
            "-Aquerydsl.entityAccessors=true",
            "-Aquerydsl.useFields=false",
            "-Aquerydsl.generatedAnnotationClass=jakarta.annotation.Generated",
            "-processor", "com.querydsl.apt.jpa.JPAAnnotationProcessor"
    ]
    options.encoding = "UTF-8"
}

tasks.named("sourcesJar").configure {
    dependsOn(tasks.named("compileJava"))
}

sourceSets {
    main { java.srcDir "$buildDir/generated/sources/annotationProcessor/java/main" }
    test { java.srcDir "$buildDir/generated/sources/annotationProcessor/java/test" }
}
